export const ANALYTICS_MIN_EVIDENCIAS_FORTALEZA = 2;
export const ANALYTICS_MIN_EVIDENCIAS_APOYO = 2;
export const ANALYTICS_MIN_EVIDENCIAS_TENDENCIA = 3;
export const ANALYTICS_MIN_EVIDENCIAS_ESTADOS = 2;

export const VENTANA_TENDENCIA_8_SEMANAS = 8;
export const VENTANA_TENDENCIA_4_SEMANAS = 4;

export const MS_POR_DIA = 1000 * 60 * 60 * 24;
export const MS_POR_SEMANA = MS_POR_DIA * 7;
